apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentflow-service.fullname" . }}
  labels:
    {{- include "agentflow-service.labels" . | nindent 4 }}
{{- with .Values.config }}
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
