services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.69.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP/meter receiver

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./infra/manifests/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3001:3000"
    volumes:
      - ./infra/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./infra/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./infra/grafana/provisioning/alerting:/etc/grafana/provisioning/alerting
      - ./infra/grafana/provisioning/notifiers:/etc/grafana/provisioning/notifiers
    depends_on:
      - prometheus
