terraform {
  required_version = ">= 1.5.0"
  required_providers {
    kind = {
      source  = "tehcyx/kind"
      version = "0.5.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.29.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.13.2"
    }
  }
}

module "kind_cluster" {
  source       = "../../modules/kind_cluster"
  cluster_name = "agentflow-local"
}

# Simplified providers using the kubeconfig generated by kind

provider "kubernetes" {
  config_path    = module.kind_cluster.kubeconfig_path
  config_context = "kind-agentflow-local"
}

provider "helm" {
  kubernetes {
    config_path    = module.kind_cluster.kubeconfig_path
    config_context = "kind-agentflow-local"
  }
}

########################
# Helm releases
########################

# Variables pour OAuth Gmail
variable "google_client_id" {
  description = "Google OAuth client ID"
  type        = string
}

variable "google_client_secret" {
  description = "Google OAuth client secret"
  type        = string
  sensitive   = true
}

resource "helm_release" "argocd" {
  name             = "argocd"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argo-cd"
  namespace        = "argocd"
  create_namespace = true
  version          = "5.53.9"

  values = [
    <<-EOF
    server:
      extraArgs:
        - "--insecure"
    EOF
  ]
}

resource "helm_release" "keycloak" {
  name             = "keycloak"
  repository       = "https://charts.bitnami.com/bitnami"
  chart            = "keycloak"
  namespace        = "keycloak"
  create_namespace = true
  version          = "18.7.1"

  values = [
    <<-EOF
    auth:
      adminUser: "admin"
      adminPassword: "admin123"
    EOF
  ]

  depends_on = [helm_release.argocd]
}

# Création d'un Kubernetes Secret pour les credentials Gmail
resource "kubernetes_secret" "gmail_oauth" {
  metadata {
    name      = "gmail-oauth"
    namespace = "default"
  }
  string_data = {
    GOOGLE_CLIENT_ID     = var.google_client_id
    GOOGLE_CLIENT_SECRET = var.google_client_secret
  }
}
