# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x86\x01\n\nRunRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x35\n\nparameters\x18\x02 \x03(\x0b\x32!.agent.RunRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1c\n\x0bRunResponse\x12\r\n\x05token\x18\x01 \x01(\t2@\n\x0c\x41gentService\x12\x30\n\x03Run\x12\x11.agent.RunRequest\x1a\x12.agent.RunResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RUNREQUEST_PARAMETERSENTRY']._options = None
  _globals['_RUNREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_RUNREQUEST']._serialized_start=23
  _globals['_RUNREQUEST']._serialized_end=157
  _globals['_RUNREQUEST_PARAMETERSENTRY']._serialized_start=108
  _globals['_RUNREQUEST_PARAMETERSENTRY']._serialized_end=157
  _globals['_RUNRESPONSE']._serialized_start=159
  _globals['_RUNRESPONSE']._serialized_end=187
  _globals['_AGENTSERVICE']._serialized_start=189
  _globals['_AGENTSERVICE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
