apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - clustersecretstore-aws.yaml
  - externalsecret-api.yaml
  - externalsecret-worker.yaml
  - externalsecret-db.yaml
  - externalsecret-ca.yaml
