########################################################################
# OTel Collector - EKS overrides.
########################################################################

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 192Mi
  limits:
    memory: 384Mi
